const dolls = [
  // ===== G1 (2010–2016) =====
  {
    id: "draculaura",
    name: "Дракулаура",
    year: 2010,
    price: 25,
    collection: "First Wave",
    image: "assets/dolls/draculaura.jpg",
    shortInfo: "Дочь Дракулы, вампир-вегетарианка.",
    character: "Добрая, романтичная",
    features: "Клыки, зонтик",
    theme: "vampire",
    animation: "bats"
  },
  {
    id: "frankie",
    name: "Фрэнки Штейн",
    year: 2010,
    price: 25,
    collection: "First Wave",
    image: "assets/dolls/frankie.jpg",
    shortInfo: "Дочь Франкенштейна.",
    character: "Энергичная, дружелюбная",
    features: "Болты, швы",
    theme: "electric",
    animation: "lightning"
  },
  {
    id: "clawdeen",
    name: "Клодин Вульф",
    year: 2010,
    price: 25,
    collection: "First Wave",
    image: "assets/dolls/clawdeen.jpg",
    shortInfo: "Оборотень и икона моды.",
    character: "Уверенная, лидер",
    features: "Волчьи уши",
    theme: "wolf",
    animation: "moon"
  },
  {
    id: "cleo",
    name: "Клео де Нил",
    year: 2010,
    price: 25,
    collection: "First Wave",
    image: "assets/dolls/cleo.jpg",
    shortInfo: "Дочь мумии, королева школы.",
    character: "Гордая, властная",
    features: "Бинты, золото",
    theme: "royal",
    animation: "sparkles"
  },
  {
    id: "lagoona",
    name: "Лагуна Блю",
    year: 2010,
    price: 25,
    collection: "First Wave",
    image: "assets/dolls/lagoona.jpg",
    shortInfo: "Дочь морского монстра.",
    character: "Дружелюбная",
    features: "Плавники",
    theme: "sea",
    animation: "bubbles"
  },

  // G1 – доп персонажи
  {
    id: "ghoulia",
    name: "Гулия Йелпс",
    year: 2010,
    price: 28,
    collection: "First Wave",
    image: "assets/dolls/ghoulia.jpg",
    shortInfo: "Зомби-интеллектуал.",
    character: "Умная, спокойная",
    features: "Очки",
    theme: "electric",
    animation: "glitch"
  },
  {
    id: "abbey",
    name: "Эбби Боминейбл",
    year: 2011,
    price: 30,
    collection: "Wave 2",
    image: "assets/dolls/abbey.jpg",
    shortInfo: "Дочь йети.",
    character: "Холодная, честная",
    features: "Лёд",
    theme: "sea",
    animation: "snow"
  },
  {
    id: "spectra",
    name: "Спектра Вондергейст",
    year: 2011,
    price: 30,
    collection: "Wave 2",
    image: "assets/dolls/spectra.jpg",
    shortInfo: "Призрак-сплетница.",
    character: "Любопытная",
    features: "Цепи",
    theme: "vampire",
    animation: "fog"
  },
  {
    id: "toralei",
    name: "Торалей Страйп",
    year: 2011,
    price: 28,
    collection: "Wave 2",
    image: "assets/dolls/toralei.jpg",
    shortInfo: "Кошка-оборотень.",
    character: "Хитрая",
    features: "Хвост",
    theme: "wolf",
    animation: "scratch"
  },
  {
    id: "nefera",
    name: "Нефера де Нил",
    year: 2012,
    price: 35,
    collection: "Wave 3",
    image: "assets/dolls/nefera.jpg",
    shortInfo: "Старшая сестра Клео.",
    character: "Манипулятивная",
    features: "Корона",
    theme: "royal",
    animation: "sparkles"
  },

  // ===== G2 (2016–2018) =====
  {
    id: "draculaura_g2",
    name: "Дракулаура (G2)",
    year: 2016,
    price: 20,
    collection: "G2 Reboot",
    image: "assets/dolls/draculaura_g2.jpg",
    shortInfo: "Обновлённый дизайн.",
    character: "Более детский стиль",
    features: "Мягкие цвета",
    theme: "vampire",
    animation: "hearts"
  },
  {
    id: "frankie_g2",
    name: "Фрэнки Штейн (G2)",
    year: 2016,
    price: 20,
    collection: "G2 Reboot",
    image: "assets/dolls/frankie_g2.jpg",
    shortInfo: "G2 версия Фрэнки.",
    character: "Наивная",
    features: "Простые швы",
    theme: "electric",
    animation: "lightning"
  },
  {
    id: "cleo_g2",
    name: "Клео де Нил (G2)",
    year: 2016,
    price: 20,
    collection: "G2 Reboot",
    image: "assets/dolls/cleo_g2.jpg",
    shortInfo: "Более мягкий образ.",
    character: "Дружелюбнее",
    features: "Меньше золота",
    theme: "royal",
    animation: "sparkles"
  },

  // ===== G3 (2022–…) =====
  {
    id: "draculaura_g3",
    name: "Дракулаура (G3)",
    year: 2022,
    price: 30,
    collection: "G3 Core",
    image: "assets/dolls/draculaura_g3.jpg",
    shortInfo: "Современный редизайн.",
    character: "Уверенная",
    features: "Новый стиль",
    theme: "vampire",
    animation: "bats"
  },
  {
    id: "frankie_g3",
    name: "Фрэнки Штейн (G3)",
    year: 2022,
    price: 30,
    collection: "G3 Core",
    image: "assets/dolls/frankie_g3.jpg",
    shortInfo: "Современный образ.",
    character: "Свободная",
    features: "Протез",
    theme: "electric",
    animation: "lightning"
  },
  {
    id: "clawdeen_g3",
    name: "Клодин Вульф (G3)",
    year: 2022,
    price: 30,
    collection: "G3 Core",
    image: "assets/dolls/clawdeen_g3.jpg",
    shortInfo: "Главная героиня G3.",
    character: "Решительная",
    features: "Очки",
    theme: "wolf",
    animation: "moon"
  },
  {
    id: "rochelle",
    name: "Рошель Гойл",
    year: 2011,
    price: 30,
    collection: "Wave 2",
    image: "assets/dolls/rochelle.jpg",
    shortInfo: "Дочь горгульи из Парижа.",
    character: "Скромная, романтичная",
    features: "Крылья",
    theme: "royal",
    animation: "feathers"
  },
  {
    id: "venus",
    name: "Венера МакФлайтрап",
    year: 2012,
    price: 32,
    collection: "Wave 3",
    image: "assets/dolls/venus.jpg",
    shortInfo: "Растительный монстр.",
    character: "Бунтарка",
    features: "Лианы",
    theme: "sea",
    animation: "leaves"
  },
  {
    id: "operetta",
    name: "Оперетта",
    year: 2012,
    price: 32,
    collection: "Wave 3",
    image: "assets/dolls/operetta.jpg",
    shortInfo: "Дочь Призрака Оперы.",
    character: "Драматичная",
    features: "Маска",
    theme: "vampire",
    animation: "notes"
  },
  {
    id: "skelita",
    name: "Скелита Калаверас",
    year: 2013,
    price: 35,
    collection: "Wave 4",
    image: "assets/dolls/skelita.jpg",
    shortInfo: "Скелет из Мексики.",
    character: "Весёлая",
    features: "Кости",
    theme: "royal",
    animation: "sparkles"
  },
  {
    id: "jinafire",
    name: "Джинафайр Лонг",
    year: 2013,
    price: 35,
    collection: "Wave 4",
    image: "assets/dolls/jinafire.jpg",
    shortInfo: "Китайский дракон.",
    character: "Гордая",
    features: "Чешуя",
    theme: "royal",
    animation: "flames"
  },
  {
    id: "viperine",
    name: "Вайперин Горгон",
    year: 2013,
    price: 34,
    collection: "Wave 4",
    image: "assets/dolls/viperine.jpg",
    shortInfo: "Дочь Медузы.",
    character: "Художница",
    features: "Змеи",
    theme: "vampire",
    animation: "glow"
  },
  {
    id: "catrine",
    name: "Катрина Демью",
    year: 2013,
    price: 34,
    collection: "Wave 4",
    image: "assets/dolls/catrine.jpg",
    shortInfo: "Кошка-художница.",
    character: "Мечтательная",
    features: "Хвост",
    theme: "wolf",
    animation: "sparkles"
  },
  {
    id: "elissabat",
    name: "Элиссабат",
    year: 2014,
    price: 36,
    collection: "Frights Camera Action",
    image: "assets/dolls/elissabat.jpg",
    shortInfo: "Вампир-актриса.",
    character: "Таинственная",
    features: "Плащ",
    theme: "vampire",
    animation: "fog"
  },
  {
    id: "twyla",
    name: "Твайла",
    year: 2013,
    price: 33,
    collection: "Wave 4",
    image: "assets/dolls/twyla.jpg",
    shortInfo: "Дочь Бугимена.",
    character: "Застенчивая",
    features: "Тени",
    theme: "vampire",
    animation: "shadows"
  },
  {
    id: "howleen",
    name: "Хаулин Вульф",
    year: 2012,
    price: 28,
    collection: "Wave 3",
    image: "assets/dolls/howleen.jpg",
    shortInfo: "Младшая сестра Клодин.",
    character: "Импульсивная",
    features: "Кудри",
    theme: "wolf",
    animation: "moon"
  },

  // ===== G2 (продолжение) =====
  {
    id: "lagoona_g2",
    name: "Лагуна Блю (G2)",
    year: 2016,
    price: 22,
    collection: "G2 Reboot",
    image: "assets/dolls/lagoona_g2.jpg",
    shortInfo: "Обновлённый морской стиль.",
    character: "Спокойная",
    features: "Пастель",
    theme: "sea",
    animation: "bubbles"
  },
  {
    id: "clawdeen_g2",
    name: "Клодин Вульф (G2)",
    year: 2016,
    price: 22,
    collection: "G2 Reboot",
    image: "assets/dolls/clawdeen_g2.jpg",
    shortInfo: "Мягкий дизайн.",
    character: "Дружелюбная",
    features: "Светлый мех",
    theme: "wolf",
    animation: "moon"
  },

  // ===== G3 (продолжение) =====
  {
    id: "cleo_g3",
    name: "Клео де Нил (G3)",
    year: 2022,
    price: 32,
    collection: "G3 Core",
    image: "assets/dolls/cleo_g3.jpg",
    shortInfo: "Новый египетский стиль.",
    character: "Уверенная",
    features: "Геометрия",
    theme: "royal",
    animation: "sparkles"
  },
  {
    id: "lagoona_g3",
    name: "Лагуна Блю (G3)",
    year: 2022,
    price: 32,
    collection: "G3 Core",
    image: "assets/dolls/lagoona_g3.jpg",
    shortInfo: "Современный океанский образ.",
    character: "Эмоциональная",
    features: "Яркие цвета",
    theme: "sea",
    animation: "bubbles"
  },
  {
    id: "toralei_g3",
    name: "Торалей Страйп (G3)",
    year: 2023,
    price: 33,
    collection: "G3 Core",
    image: "assets/dolls/toralei_g3.jpg",
    shortInfo: "Новый характер и дизайн.",
    character: "Саркастичная",
    features: "Полоски",
    theme: "wolf",
    animation: "scratch"
  }
];
